VIA_ENABLE = yes
VIAL_ENABLE = yes

LTO_ENABLE = yes
OLED_ENABLE = no
RGB_MATRIX_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
